name: Build
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-node@v4.0.1 # this installs node and npm for us
      with:
        node-version: '20.10.0'
    - uses: actions/cache@v3.3.2 # this allows for re-using node_modules caching, making builds a bit faster.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - run: npm install
    - run: npm install -g @angular/cli > /dev/null
    - run: ng build --configuration production

    # push the /dist folder to your repo
    - name: Commit changes
      uses: EndBug/add-and-commit@v9.1.3
      with:
        default_author: github_actions
        message: 'Updating /dist'
        add: '.'
